from __future__ import annotations

raise Exception("After error")
